println("Listen and hear a song the birds are singing");
println("Sit down a while and watch the flowers blooming");
println("Aplesant breeze flows by leaving a trail of dust");
println("This is your fault right?");
println("Standing in the corridor");
println("Who tought we'd be here like this together?");
println("On a day like this, i ask,");
println("What is it that you want?");
println(" ");
println("I believe there was a time where");
println("Where we could be pals and things were better.");
println("Eating bad food, enjoying laughs.");
println("Can we go back to that?");
println("If your in there listening, kid,");
println("Just reset the timeline and.");
println("Lets please forget all of this.");
println("Even after what you did he believed in you'til the end.");
println("Looking at your face right now,");
println("That expression tells me i cant afford not to care anymore");
println("Turn this path around, wipe your dirty hands clean");
println("give.");
println("up.");
println("Please dont... come.. back");
println(" ");
println("If your my friend");
println("...");
println("Please");
println("Listen to a song the birds are singing");
println("Sit down a while and watch the flowers blooming");
println("A plesant breeze flows by leaving a trail of- (dust)");
println("How could you have done this?");
println("...");
println("Is there still,");
println("A glimmer of hope?");
println("Will you choose to do the right?");
println("Please, now bud?");
println("If you're there");
println("Have a chance of heart");
println("Listen and hear a song the birds are singning");
println("Sit down a while and watch the flowers blooming");
println("What a nice day...");
